apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      version: "9.2.10"
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: flux-system
  values:
    service:
      type: ClusterIP
      port: 80
    persistence:
      enabled: true
      size: 10Gi
    adminUser: admin
    adminPassword: admin123
    ingress:
      enabled: true
      hosts:
        - grafana.company.com
