apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: full-stack
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: prometheus
            repoURL: https://github.com/AntonioJordan/cicdcompletelab-argocd
            targetRevision: HEAD
            path: apps/prometheus
            namespace: monitoring
            helm:
              valueFiles:
                - ../../values.yaml
          - name: grafana
            repoURL: https://github.com/AntonioJordan/cicdcompletelab-argocd
            targetRevision: HEAD
            path: apps
            namespace: grafana/monitoring
            helm:
              valueFiles:
                - ../../values.yaml
          - name: frontend
            repoURL: https://github.com/AntonioJordan/cicdcompletelab-openshift
            targetRevision: HEAD
            path: helm-templates
            namespace: react-app
            helm:
              valueFiles:
                - values.yaml
  template: {}
