apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: default
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: prometheus
            repoURL: https://github.com/AntonioJordan/cicdcompletelab-argocd
            namespace: monitoring
            path: apps/prometheus
          - appName: grafana
            repoURL: https://github.com/AntonioJordan/cicdcompletelab-argocd
            path: apps/grafana
            namespace: monitoring
          # - appName: frontend
          #   repoURL: https://github.com/AntonioJordan/cicdcompletelab-openshift
          #   targetRevision: HEAD
          #   path: helm-templates
          #   namespace: react-app
          #   helm:
          #     valueFiles:
          #       - values.yaml

  template:
    metadata:
      name: "{{appName}}"
    spec:
      project: default
      source:
        repoURL: "{{repoURL}}"
        targetRevision: HEAD
        path: "{{path}}"
        helm:
          releaseName: "{{appName}}"
          valueFiles:
          - "values.yaml"
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true
