apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: default
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: prometheus
            repoURL: https://github.com/AntonioJordan/cicdcompletelab-argocd
            namespace: monitoring
            path: apps/prometheus
            extraValues: |
              {}
          - appName: grafana
            repoURL: https://github.com/AntonioJordan/cicdcompletelab-argocd
            namespace: monitoring
            path: apps/grafana
            extraValues: |
              service:
                type: NodePort
                nodePort: 32000
                enabled: true

  template:
    metadata:
      name: "{{appName}}"
    spec:
      project: default
      source:
        repoURL: "{{repoURL}}"
        targetRevision: HEAD
        path: "{{path}}"
        helm:
          values: |
            {{extraValues}}
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true
