apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: full-stack
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: prometheus
            repoURL: https://github.com/AntonioJordan/cicdcompletelab-argocd
            targetRevision: HEAD
            path: apps/prometheus
            namespace: monitoring
          - name: grafana
            repoURL: https://github.com/AntonioJordan/cicdcompletelab-argocd
            targetRevision: HEAD
            path: apps/grafana
            namespace: monitoring
          - name: frontend
            repoURL: https://github.com/AntonioJordan/cicdcompletelab-openshift
            targetRevision: HEAD
            path: helm-templates
            namespace: react-app
            helm:
              valueFiles:
                - react-values.yaml
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true
