apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-repo-server
    spec:
      volumes:
        - name: var-files
          emptyDir: {}
        - name: plugins
          emptyDir: {}
      initContainers:
        - name: copyutil
          image: quay.io/argoproj/argocd:v3.0.6
          command: ["/bin/cp", "-n", "/usr/local/bin/argocd", "/var/run/argocd/argocd-cmp-server"]
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
      containers:
        - name: argocd-repo-server
          image: quay.io/argoproj/argocd:v3.0.6
          command: ["/usr/local/bin/argocd-repo-server"]
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
        - name: cmp-helm-custom
          image: quay.io/argoproj/argocd:v3.0.6
          command: ["/var/run/argocd/argocd-cmp-server"]
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
