apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
data:
  configManagementPlugins: |
    - name: helm-custom
      init:
        command: [sh, -c, "helm dependency build"]
      generate:
        command: [sh, -c, "./.argocd-plugins/helm-custom.sh"]
