apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 6.32.0
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: flux-system
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      storage:
        type: filesystem
    persistence:
      enabled: true
      accessModes: ["ReadWriteOnce"]
      size: 10Gi
      storageClassName: standard
    serviceMonitor:
      enabled: true
    podMonitor:
      enabled: true
