apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 6.32.0
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: flux-system
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: "2022-01-01"
            store: boltdb-shipper
            object_store: filesystem
            schema: v12
            index:
              prefix: index_
              period: 24h
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        size: 10Gi
    serviceMonitor:
      enabled: true
    podMonitor:
      enabled: true
