apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 5.44.0
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: flux-system
  values:
    mode: monolith
    loki:
      auth_enabled: false
      storage:
        type: filesystem
    singleBinary:
      replicas: 1
    persistence:
      enabled: true
      storageClassName: standard
      accessModes: ["ReadWriteOnce"]
      size: 10Gi
    serviceMonitor:
      enabled: true
    podMonitor:
      enabled: true
