apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 6.32.0
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: loki-values
      valuesKey: values.yaml
