deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    filesystem:
      directory: /tmp/loki/chunks
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  ruler:
    enable_api: true
  metrics:
    enabled: true
    listen_address: 0.0.0.0:9095

server:
  http_listen_port: 3100

minio:
  enabled: false
singleBinary:
  replicas: 1
  persistence:
    storageClass: standard
    accessModes:
      - ReadWriteOnce
    size: 20Gi
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
sidecar:
  image:
    repository: kiwigrid/k8s-sidecar
    tag: 1.30.0
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
chunksCache:
  allocatedMemory: 500

metricsGenerator:
  enabled: true
  
service:
  ports:
    - name: metrics-generator
      port: 3101
      targetPort: 3101