apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      version: "9.2.10"
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: grafana-values
      valuesKey: values.yaml
