apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease-grafana.yaml

configMapGenerator:
  - name: grafana-values
    namespace: monitoring
    files:
      - values.yaml
