adminUser: guest
adminPassword: guest

service:
  type: NodePort
  nodePort: 32000

grafana.ini:
  users:
    default_theme: light

plugins:
  - marcusolsson-json-datasource

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy
        isDefault: false
        editable: true


dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: node-exporter
        orgId: 1
        folder: NodeExporter
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/node-exporter
      - name: nginx
        orgId: 1
        folder: NGINX
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/nginx

extraVolumeMounts:
  - name: node-exporter-dashboard
    mountPath: /var/lib/grafana/dashboards/node-exporter
    readOnly: true
  - name: nginx-dashboard
    mountPath: /var/lib/grafana/dashboards/nginx
    readOnly: true

extraVolumes:
  - name: node-exporter-dashboard
    configMap:
      name: node-exporter-dashboard
  - name: nginx-dashboard
    configMap:
      name: nginx-dashboard
