adminUser: guest
adminPassword: guest

service:
  type: NodePort
  nodePort: 32000

grafana.ini:
  users:
    default_theme: light

plugins:
  - marcusolsson-json-datasource

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: graph-node-exporter
        orgId: 1
        folder: 'NodeExporter'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/graph-node-exporter

dashboards:
  graph-node-exporter:
    node-exporter:
      file: grafana-dashboards/node-exporter.json
