adminUser: guest
adminPassword: guest

service:
  type: NodePort
  nodePort: 32000

plugins:
  - marcusolsson-json-datasource

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true
