apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana-agent
      version: 0.37.0
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: flux-system
  values:
    controller:
      type: daemonset
    agent:
      configMap:
        create: true
        content: |
          server:
            log_level: info
          receivers:
            filelog:
              include: [/var/log/**/*.log]
              start_at: beginning
          exporters:
            loki:
              endpoint: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
          service:
            pipelines:
              logs:
                receivers: [filelog]
                exporters: [loki]
    extraVolumes:
      - name: varlog
        hostPath:
          path: /var/log
    extraVolumeMounts:
      - name: varlog
        mountPath: /var/log
