nodeExporter:
  enabled: true

rbac:
  create: true

configmapReload:
  prometheus:
    image:
      tag: v0.83.0

server:
  extraFlags:
    - web.enable-lifecycle
  global:
    scrape_interval: 1m
    scrape_timeout: 10s
    evaluation_interval: 1m
  persistentVolume:
    size: 10Gi
    storageClass: standard
  retention: "15d"
  service:
    type: NodePort
    nodePort: 31058

serverFiles:
  recording_rules.yml:
    groups:
      - name: recording-rules
        rules:
          - record: job:cpu_usage:rate5m
            expr: rate(node_cpu_seconds_total{job="kubernetes-service-endpoints"}[5m])
          - record: job:up_zero
            expr: up == 0
  prometheus.yml:
    rule_files:
      - /etc/config/recording_rules.yml
      - /etc/config/alerting_rules.yml
    scrape_configs:
      - job_name: 'nginx-exporter-react-app'
        static_configs:
          - targets:
              - nginx-exporter-svc.react-app.svc.cluster.local:9113
      - job_name: 'node-exporter'
        static_configs:
          - targets:
              - prometheus-prometheus-node-exporter.monitoring.svc.cluster.local:9100
      - job_name: 'loki'
        static_configs:
          - targets:
              - loki.monitoring.svc.cluster.local:3100

alertmanager:
  enabled: true
  persistence:
    size: 2Gi

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

prometheus-pushgateway:
  enabled: true
  serviceAnnotations:
    prometheus.io/probe: pushgateway
