apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mi-chart
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/AntonioJordan/cicdcompletelab-openshift
  ref:
    branch: main
