apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  releaseName: elasticsearch
  chart:
    spec:
      chart: elasticsearch
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      version: "7.17.3"
  interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: elastic-search-values
      valuesKey: values.yaml
  values:
    resources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "1"
        memory: "3Gi"
    volumeClaimTemplate:
      storageClassName: standard
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
    replicas: 1
    minimumMasterNodes: 1
    esJavaOpts: "-Xms1g -Xmx1g"
