replicas: 1
minimumMasterNodes: 1

esJavaOpts: "-Xms1g -Xmx1g"

volumeClaimTemplate:
  storageClassName: standard
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 1
    memory: 3Gi
